name = "FunctionMaps"
uuid = "a75834df-64dc-405c-a530-e22a155ff74e"
authors = ["Daan Huybrechs <daan.huybrechs@kuleuven.be> and contributors"]
version = "0.1.0"

[deps]
CompositeTypes = "b152e2b5-7a66-4b01-a709-34e65c35f657"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = "1.6"
Aqua = "0.8"
CompositeTypes = "0.1.3"
LinearAlgebra = "1"
StaticArrays = "1"
Test = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua"]
